---
- hosts: localhost
  tasks:
    - name: Provide information about vCenter
      vmware_about_facts:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
      delegate_to: localhost
      register: vcenter_about_info
    - debug:
        msg: Hello from {{ vcenter_about_info.about_facts.instance_uuid }}
