---
#
#   (C) Copyright 2017 Hewlett Packard Enterprise Development LP.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

- name: Create secrets
  shell: echo -n "{{ minio_access_key }}" | docker secret create access_key -
- shell: echo -n "{{ minio_secret_key }}" | docker secret create secret_key -

- name: Deploy Minio
  get_url:
    url: "{{ minio_stack_url }}"
    dest: ~/stack.yml
- command: docker stack deploy -c ~/stack.yml "{{ swarm_app_name }}_stack"

- name: Wait until online...
  command: docker service ps {{ item }}
  with_items:
    - "{{ swarm_app_name }}_stack_minio1"
    - "{{ swarm_app_name }}_stack_minio2"
    - "{{ swarm_app_name }}_stack_minio3"
    - "{{ swarm_app_name }}_stack_minio4"
  register: deployed
  until: deployed | success

- name: ...and add constraints
  shell: docker service ps {{ item }} --format "{{'{{'}} .Node {{'}}'}}" \
         | xargs -n1 -I% docker service update --detach=false --constraint-add 'node.hostname == %' {{ item }} 
  with_items:
    - "{{ swarm_app_name }}_stack_minio1"
    - "{{ swarm_app_name }}_stack_minio2"
    - "{{ swarm_app_name }}_stack_minio3"
    - "{{ swarm_app_name }}_stack_minio4"
